x-backend-mount: &backend-mount
    './backend:/var/www/html/backend'
x-xdebug-config-mount: &xdebug-config-mount
    './docker/php/conf.d/zz-xdebug.ini:/etc/php/8.5/cli/conf.d/zz-xdebug.ini'
x-backend-env: &backend-env
    SUPERVISOR_PHP_COMMAND: ${SUPERVISOR_PHP_COMMAND}
    XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=127.0.0.1}'
    IGNITION_LOCAL_SITES_PATH: '${PWD}'
    XDEBUG_TRIGGER: 1
    DB_DATABASE: '${DB_DATABASE}'
    DB_USERNAME: '${DB_USERNAME}'
    DB_PASSWORD: '${DB_PASSWORD:-secret}'

x-backend-depends: &backend-depends
    - pgsql
    - redis

x-app-base: &app-base
    restart: unless-stopped
    build:
        context: './backend/vendor/laravel/sail/runtimes/8.5'
        dockerfile: Dockerfile
        args:
            WWWGROUP: '${WWWGROUP}'
    image: 'app'
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    environment:
        WWWUSER: '${WWWUSER}'
        LARAVEL_SAIL: 1
    networks:
        - sail

services:
    fe:
        <<: *app-base
        depends_on:
            - app
        working_dir: /var/www/html/frontend
        command: npm run dev
        volumes:
            - './frontend:/var/www/html/frontend'
        ports:
            - ${FE_PORT:-5173}:5173
        
    app:
        <<: *app-base
        depends_on: *backend-depends
        volumes:
            - *backend-mount
            - *xdebug-config-mount
        working_dir: /var/www/html/backend
        environment: *backend-env
        ports:
            - '${APP_PORT:-80}:80'
    queue:
        <<: *app-base
        depends_on: *backend-depends
        volumes:
            - *backend-mount
            - *xdebug-config-mount
            - './docker/supervisord-queue.conf:/etc/supervisor/conf.d/supervisord.conf'
        working_dir: /var/www/html/backend
        environment: *backend-env
    pgsql:
        image: 'postgres:18-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql'
            - './backend/vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    graylog:
        image: 'graylog/graylog'
        
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
